// The player guide. One source for the main menu's guide and the pause menu's "How to play".
// Each chapter is { id, icon, title, html }. Keep it practical: what to press, where to go, what to do when stuck.
window.RF_GUIDE = [
  { id: 'start', icon: '🌱', title: 'Your first ten minutes', html:
    '<p>You start with <b>$220</b>, a small tent, one pot and an empty shop. The goal of the first session is one full loop: seed to sale.</p><p>A brand new shop is walked through exactly that by the <b>guided intro</b>, a card on the left of the screen that ticks off nine steps as you do them. Finish all nine and <b>$2,500</b> goes into the bank. You can switch it off any time under <b>Guided intro</b> in the pause menu, though skipping costs you the bonus.</p>' +
    '<ol><li>Walk to the <b>office laptop</b> (the room left of the hall). Order <b>soil</b>, a <b>seed</b>, <b>baggies</b> and, when you can afford it, a <b>grinder</b>.</li>' +
    '<li>Orders come by van to the back. What arrives ends up on the <b>supply rack</b> beside the laptop or as crates in the back room storage; carry crates to the rack yourself, or hire Jo later to do it.</li>' +
    '<li>Take a bag of soil to the <b>grow tent</b>, fill the pot, fetch the seed from the rack, plant it.</li>' +
    '<li>When the plant says thirsty, grab the <b>watering can</b> next to the tent. Feed <b>nutrients</b> once for quality. Spray pests or mold quickly.</li>' +
    '<li>A glowing <b>READY</b> plant is harvested with empty hands. Carry the bunch to the <b>drying line</b> in the dry room and hang it.</li>' +
    '<li>Dried batches jar themselves on the <b>curing shelf</b> and keep gaining quality. Carry a jar to the <b>workbench</b> in the processing room and empty it into the stash.</li>' +
    '<li>At the bench: <b>bag</b> eighths, <b>roll</b> joints (papers and tips), later <b>bake</b> cookies. Finished goods appear on the <b>goods shelf</b>.</li>' +
    '<li>Open the shop at the <b>shop control box</b> (security room, or wherever you hung it). Customers come to the <b>service window</b>. Pick what they asked for off the goods shelf, hand it through the window, then take payment at the <b>register</b>.</li></ol>' +
    '<p>That is the whole game in miniature. Everything else makes that loop bigger, faster or more dangerous.</p>' },
  { id: 'keys', icon: '⌨️', title: 'Controls', html:
    '<table><tr><td><b>W A S D</b></td><td>move</td></tr><tr><td><b>Shift</b></td><td>run</td></tr><tr><td><b>E</b> or left click</td><td>use, pick up, talk, hand over</td></tr><tr><td><b>Shift + E</b></td><td>the second action: lock or unlock a door or a cabinet with the keyring, the car trunk, a staff menu</td></tr>' +
    '<tr><td><b>G</b> or <b>Q</b></td><td>put back what you hold</td></tr><tr><td><b>1 to 6</b>, mouse wheel</td><td>hotbar slot</td></tr><tr><td><b>Tab</b></td><td>inventory</td></tr><tr><td><b>M</b></td><td>town map</td></tr>' +
    '<tr><td><b>J</b></td><td>the delivery boards: the burner phone and the tablet</td></tr><tr><td><b>P</b></td><td>silent alarm (needs the upgrade)</td></tr><tr><td><b>F2</b></td><td>edit mode: move furniture, signs, screens</td></tr><tr><td><b>F3</b></td><td>creative build mode</td></tr><tr><td><b>Right click</b></td><td>close the open menu or panel</td></tr>' +
    '<tr><td><b>F7</b></td><td>report a bug</td></tr><tr><td><b>Esc</b></td><td>pause menu</td></tr><tr><td><b>F11</b></td><td>fullscreen (desktop app)</td></tr></table>' +
    '<p><b>In the car:</b> <b>I</b> turns the key, <b>P</b> is the handbrake, <b>L</b> cycles the lights, W and S drive, A and D steer, Space is the footbrake, <b>T</b> pops the boot, <b>B</b> the bonnet, the mouse swings the camera round the car, the wheel zooms, <b>C</b> re-centres, <b>E</b> gets out once you have stopped.</p><p><b>With a weapon in hand:</b> left click swings or fires.</p>' },
  { id: 'grow', icon: '🪴', title: 'Growing and quality', html:
    '<p>Quality is the number that decides your prices and whether connoisseurs buy at all.</p>' +
    '<ul><li><b>Water</b> on time. A thirsty plant loses quality.</li><li><b>Nutrients</b> once per plant: a flat quality bonus.</li><li><b>Pests and mold</b> are hazards: spray them with remedy at once.</li><li><b>Humidity</b>: drying is faster below 55 percent, mold spreads above 60. The dehumidifiers are set at the shop control box.</li><li><b>Lights and tents</b> are bought at the laptop. Bigger tents need the cultivation permits.</li><li><b>Curing</b>: jars keep improving on the shelf. Patience is quality.</li></ul>' +
    '<p>Rough, low quality bud is not wasted. The <b>extraction lab</b> turns any quality into carts, hash, gummies and chocolate. The <b>roof greenhouse</b> grows exactly that kind of bud for free.</p>' },
  { id: 'sell', icon: '🛎️', title: 'Selling', html:
    '<ul><li>An order can have several lines. Hand over each line; the customer pays when it is complete.</li><li>Asked for a strain you do not have? Another strain of the same kind is accepted at 15 percent off. Connoisseurs refuse substitutes and anything under their quality bar.</li>' +
    '<li><b>Cash</b> customers need change from the register. <b>Card</b> needs the retail licence.</li><li>Small extras (lighters, papers, grinders) sit on the counter display and customers help themselves.</li>' +
    '<li><b>Cigarettes, carts, hash, gummies and chocolate</b> are kept in the <b>cabinet behind the counter</b>. Roll the shutter up, take what they asked for, hand it over yourself. It goes on the same bill.</li>' +
    '<li>The <b>markup</b> slider at the control box trades price against footfall.</li><li>Rain, storms and snow thin the street out. Weekends are busier, and there is a holiday week.</li></ul>' },
  { id: 'money', icon: '💵', title: 'Money and the bank', html:
    '<p>Money sits in places: the <b>till</b>, the <b>tip jar</b>, machine cash boxes, your <b>pocket</b>, the <b>vault</b> and the <b>bank</b>. Only the bank is safe and only the bank pays for orders and licences.</p>' +
    '<ul><li>Empty the till into your pocket, then put it in the office <b>vault</b>.</li><li>Book a <b>courier</b> in the bank app: he collects from your pocket at the back door, and it clears the next day.</li><li>Or drive to <b>First Harvest Bank</b> in town and pay it in yourself: instant and free.</li><li>A robber takes what is in the till and tip jar. A gunman goes for the vault next. Pocket cash is lost if you are knocked down, and inspections fine you on it when police heat is high.</li></ul>' },
  { id: 'staff', icon: '🧑‍🔧', title: 'Staff', html:
    '<ul><li><b>Jo</b> (hired at the laptop): serves the window, restocks, sweeps or tends plants. Shift + E on Jo changes the job.</li><li><b>Security guard</b>: checks ID at the door; send him on patrol to deter robbers and break up fights sooner.</li>' +
    '<li>The <b>staff roster</b> board in the office hires three more: a <b>driver</b> (wholesales your cartons every morning and runs phone deliveries), a <b>basement operator</b> (keeps the cigarette line running) and a <b>night guard</b> (stops break-ins).</li><li>Wages leave the bank at the start of each day.</li></ul>' },
  { id: 'crime', icon: '🚨', title: 'Robberies, weapons and the police', html:
    '<p>Robberies run in stages: someone <b>cases</b> the lobby, the <b>mask</b> comes down, the <b>demand</b> at the window, an <b>escalation</b>, sometimes a <b>second target</b> in the back, then the <b>getaway</b>.</p>' +
    '<ul><li>While he is only casing, walk up and press E to confront him. Often he just leaves.</li><li>During the demand, E on the register hands the till over and nobody gets hurt.</li><li>Four kinds, growing with your shop: snatch thief, knife robber, gunman (goes for the vault), two man crew (the bagman strips your goods shelf, and the cabinet if its shutter is up).</li>' +
    '<li><b>Weapons</b>: the bat by the counter is free. The <b>weapon locker</b> sells pepper spray, a taser, and with the firearms licence a pistol and a shotgun. Non lethal tools can fail against dangerous robbers; when they do, he hits back and you go down.</li>' +
    '<li>Shooting an armed, masked robber is self defence. Shooting a fleeing or unarmed man is a fine. Shooting a bystander costs the licence and the guns.</li><li>A robber who escapes with loot jumps into a <b>black car</b> on Main Street. Ram it with yours and everything comes back.</li>' +
    '<li><b>Silent alarm</b> upgrade: press P, police arrive in about 20 seconds.</li><li><b>Doors</b> can be shut and locked from the control box, or at the door itself with the keyring. Staff carry keys; a robber forces a locked door and breaks its lock.</li><li><b>Lock your stock away.</b> The goods shelf, the cigarette cabinet and the weapon locker all have a roll gate and a lock. A robber who reaches a locked one gets nothing from it, so locking up before closing, or the moment a mask comes down, is the cheapest insurance in the game.</li>' +
    '<li><b>Police heat</b> rises with park deals, fines and shootings and cools with time. At 60 and over you get inspections. The precinct in town shows your heat and takes donations.</li></ul>' },
  { id: 'basement', icon: '🏭', title: 'The basement: RF Smoking', html:
    '<p>The steel hatch in the hall leads down to a pre installed cigarette line. You need the <b>tobacco manufacturing licence</b> to switch anything on.</p>' +
    '<ol><li><b>Bays</b>: sow ($20), wait a few minutes, cut the leaf.</li><li><b>Kiln</b>: cures up to 8 kg a load; leaf dries to a fifth of its weight. Left on, it reloads itself.</li><li><b>Shredder</b> cuts the cured leaf.</li><li><b>Maker</b> rolls Normal or Light sticks.</li><li><b>Packer</b> boxes 10s or 20s and needs paper, filters and blanks, ordered from its own menu.</li><li>Take cartons from the <b>finished goods rack</b> up to the cabinet behind the counter.</li></ol>' +
    '<p>The line makes far more than the window sells. Load cartons into your car at the garage bay (Shift + E on the car) and sell them to the <b>Corner Tobacconist</b> in town, or hire the driver.</p>' },
  { id: 'lab', icon: '🧪', title: 'The extraction lab', html:
    '<p>Its door is on the basement\'s left wall. It takes cured bud of <b>any quality</b> from your stash.</p><ul><li>10 g makes 3 vape carts, or 4 g of pressed hash.</li><li>5 g plus one baking mix makes 12 gummies or 8 chocolate bars.</li><li>One batch at a time. Collect the result from the same equipment and stock it in the cabinet behind the counter.</li><li>A power cut pauses the lab unless you own the generator.</li></ul>' },
  { id: 'town', icon: '🚗', title: 'The town, the car and the map', html:
    '<p>Your car is parked in the owner bay in the yard, behind the gate. The gate opens for it. Press <b>M</b> anywhere for the map.</p>' +
    '<p><b>Driving it.</b> Press <b>E</b> on the driver door to get in. The car starts dead: <b>I</b> turns the key, <b>P</b> lets the handbrake off, then W and S drive and A and D steer. Space is the footbrake. <b>L</b> cycles dipped headlights and main beam, which you will want after dark. The dashboard at the bottom of the screen gives you speed, revs, the gear, and lamps for the handbrake, the lights, the ignition and anything left open. Moving the mouse swings the camera round the car, the wheel pulls it in and out, and <b>C</b> puts it back behind you.</p>' +
    '<p><b>Doors and the boot.</b> Outside the car, <b>E</b> on the passenger door, the boot lid or the bonnet opens and closes it; inside, <b>T</b> is the boot and <b>B</b> the bonnet. What is in the boot sits in the boot, so you can see it. Drive off with something open and the dash warns you and the car will not go over 8 km/h. Getting out always puts the handbrake on and stops the engine.</p>' +
    '<ul><li><b>First Harvest Bank</b>: pay in, withdraw.</li><li><b>Iron and Oak Arms</b>: cheaper ammunition, a Kevlar vest.</li><li><b>RF Supply Co.</b> on the back street: supplies 20 percent cheaper, straight into your trunk. Unload at your bay.</li><li><b>Corner Tobacconist</b>: buys cartons wholesale.</li>' +
    '<li><b>Green Leaf</b>: the rival. Flyer them for reputation; at 150 rep you can buy them out for a daily income.</li><li><b>Harvest Park</b>: street deals at 35 percent over shop price, cash in pocket, with a real risk of a bust.</li><li><b>Police precinct</b>: your heat.</li></ul>' +
    '<p><b>Deliveries</b> come on two devices, and <b>J</b> opens both. See the chapter on them below. The <b>garage</b> (Shift + E on the car in its bay) fits a bigger trunk, a tuned engine and a bull bar.</p>' },
  { id: 'rounds', icon: '🚚', title: 'Deliveries: the burner and the tablet', html:
    '<p>Two devices, one key. <b>J</b> opens the board anywhere, on foot or at the wheel, and it has a tab for each.</p>' +
    '<h4>📱 The burner</h4><p>Always in your pocket. Somebody rings for <b>joints, bags or cookies</b> once you have a couple packed, gives an address across town and five minutes. Carry the goods <b>in your hands</b>, drive or walk to the green beacon and press <b>E</b>. The money is cash straight into your <b>pocket</b> at 60 percent over shop price, and it puts your <b>heat</b> up. No receipt, no tax, and a robber can take it off you, so bank it.</p>' +
    '<h4>📋 The tablet</h4><p>It sits on its dock in the office and wakes up the moment you hold the <b>tobacco licence</b>. Press <b>E</b> to take it; carry it into the car and it drops into the dash cradle, so it rides the round without eating a hotbar slot. Press <b>E</b> on the dock again to put it back.</p>' +
    '<p>The tablet lists up to four <b>RF Smoking</b> orders at once: an address, how many packs of which cigarette, what it pays and how long is left. Load the packs into the car at your bay (<b>Shift + E</b> on the car), drive the round, and pull up at the amber marker. <b>You do not have to get out</b>: stop within a few metres and the dashboard offers the drop, and <b>E</b> hands it over from the driver\'s seat. The packs come <b>out of the boot</b>, so you never carry them. The money is <b>invoiced to the bank</b>, no heat, and each drop is a point of reputation. Jobs further out pay more for the drive.</p>' +
    '<p>Every drop is marked on the ground with a coloured ring under its beacon, and the numbers on the board match the numbers on the <b>map</b> (M). Amber is a tablet drop, green a burner one. Miss a deadline and you lose a point of reputation. A hired <b>driver</b> clears jobs himself after about a minute, taking a cut of the tablet ones.</p>' },
  { id: 'workshop', icon: '🧩', title: 'The Workshop: content packs', html:
    '<p>The <b>Workshop</b> is on the main menu. Content packs change what the game has in it: more strains to grow, more lamps and tents, more to sell off the counter, more town, a different car, snow at Christmas or fireworks at New Year. Turn one on and the shop reloads. Your save is not touched, because a pack only adds things you can then go and buy.</p>' +
    '<p><b>Bundles</b> switch several packs on at once. Packs marked <i>one at a time</i> (the balance, seasonal and vehicle ones) replace each other, so you always have exactly one of each.</p>' +
    '<h4>Making your own</h4>' +
    '<p>A pack is a single <b>.json</b> file. Use <b>Save a starter .json</b> in the Workshop to get one to edit, then <b>Import a pack</b> to bring it in. It can add:</p>' +
    '<ul><li><b>strains</b>: a whole new plant, with its cost, grow time, yield, strength, unlock level and colours.</li>' +
    '<li><b>lights</b> and <b>tents</b> for the grow room.</li>' +
    '<li><b>supplies</b>: anything you order at the laptop, including things for the counter display or the vending machine.</li>' +
    '<li><b>places</b>: a building and a shopfront anywhere in town, with either a counter that sells supplies at a discount, or a service you pay for that moves your heat and reputation. The grocery and the cinema in City Life are nothing more than that.</li>' +
    '<li><b>city</b>: how much bigger the map is, and how many extra blocks fill it.</li>' +
    '<li><b>vehicle</b>: the paint, top speed and boot size of the car in your bay.</li>' +
    '<li><b>tune</b>: what seeds and upgrades cost, and how busy the shop is.</li></ul>' +
    '<h4>Models from Blender</h4>' +
    '<p>Make the object in Blender, then <b>File, Export, glTF 2.0</b> and choose <b>glTF Binary (.glb)</b>. One metre in Blender is one metre in the game, +Y is up, and the object should sit on the origin. Name the slot it replaces in the pack\'s <b>models</b> section, for example <b>item:joints</b> or <b>item:can</b>, and select the .json and the .glb files together when you import. The model then stands in for whatever the game would have built by hand.</p>' +
    '<p>Packs that ship with the game cannot be overwritten, so give yours your own id.</p>' },
  { id: 'upstairs', icon: '🏠', title: 'Upstairs and the roof', html:
    '<ul><li>The <b>office stairs</b> lead to your flat: kitchen, table, couch and TV, bed. Eating gives a speed buff; the bed passes the night.</li><li>The <b>lobby stairs</b> lead to the <b>connoisseur lounge</b>. With the connoisseur permit, guests book it, walk up on their own and wait to be served quality 70 or better. They pay triple and tip.</li><li>A ladder in the flat climbs to the <b>roof greenhouse</b>: six free beds that grow in daylight only.</li></ul>' },
  { id: 'keys', icon: '🔑', title: 'The keyring, doors and locking up', html:
    '<p>A keyring hangs on a hook in the <b>office</b>, by the door to the hall. Press E to take it; G puts it back on the hook. It is yours alone, so keep hold of it when trouble starts.</p>' +
    '<ul><li><b>Shift + E on a door</b> locks or unlocks it, wherever you are standing. Plain <b>E</b> slides a door open or shut as usual, and a locked door will not budge.</li>' +
    '<li><b>Shift + E on the goods shelf, the cigarette cabinet or the weapon locker</b> locks it. Locking rolls the gate down; unlocking lets you roll it up again with E.</li>' +
    '<li>Without the keyring you can still open and shut anything that is unlocked. You simply cannot lock or unlock.</li>' +
    '<li>The shop control box lists every door with its own shut and lock buttons, plus lock all and unlock all, if you would rather do it from one place.</li>' +
    '<li>Jo and the guard carry their own keys and walk through locked doors. A robber has to force one, which costs him time.</li></ul>' },
  { id: 'machines', icon: '🥤', title: 'Machines: vending, coffee, arcade, fridge', html:
    '<p>Four machines earn on their own, and you can own more than one of each: up to four vending machines, four coffee machines, four arcade cabinets and three fridges. Buy extras at the laptop under <b>Gear</b>, in the <b>Machines</b> box. Each one costs more than the last.</p>' +
    '<ul>' +
    '<li>A machine you buy lands beside the one you already have, in the first clear space along the same wall. Press <b>F2</b> and drag it wherever you actually want it: where you leave it is where it stays.</li>' +
    '<li>Every machine is its own machine. Its door, its delivery tray, the cup under its spout and the cans on its shelves belong to it alone. Open one and the others stay shut.</li>' +
    '<li>Stock and money are the shop\'s, not the machine\'s. All your vending machines sell from the same drinks and snacks, all your coffee machines pour from the same cups and beans, and each kind pays into one cash box. Empty it at any of them.</li>' +
    '<li>The drinks fridge is the exception: each fridge holds its own cans, because you load it by hand with a case of drinks.</li>' +
    '<li>Extra vending machines come in their own livery, so a row of them does not look like the same machine four times.</li>' +
    '<li>The coffee machine needs the <b>Lobby coffee machine</b> upgrade before you can buy a second; vending and coffee need the <b>Vending &amp; catering permit</b>, and the arcade the <b>Amusement permit</b>.</li>' +
    '<li>Customers who stay for a while will use whichever of your machines they fancy, so more machines means fewer of them queueing at one.</li>' +
    '</ul>' },
  { id: 'build', icon: '🛠️', title: 'Making the place yours', html:
    '<ul><li><b>F2 edit mode</b>: look at furniture, E grabs, R turns, E drops, Backspace resets. It also carries <b>signs, the dashboard screen, the staff roster, the key hook and the control box</b>: those stick flat to whatever surface you look at, at any height.</li><li><b>F3 creative mode</b>: a catalogue of furniture and building pieces with finishes and colours. C opens the catalogue, R rotates, the wheel raises, P paints, X copies, Del removes.</li><li>Every door slides with E and can be locked from the control box.</li></ul>' },
  { id: 'stuck', icon: '🧭', title: 'I am stuck', html:
    '<ul><li><b>No customers.</b> Is the shop open at the control box? After a police fine customers stay away for a couple of minutes. Bad weather thins them out.</li><li><b>I cannot pick something up.</b> Hands full: G puts things back, 1 to 6 switches slot.</li><li><b>The customer refuses my goods.</b> Wrong kind, or a connoisseur below his quality bar.</li>' +
    '<li><b>The machines will not start.</b> Tobacco line: you need the licence. Everything stops in a power cut without a generator.</li><li><b>I cannot buy a gun.</b> Firearms licence first (level 4, reputation 30).</li><li><b>My car is wedged.</b> Reverse with S and swing the wheel. The yard is tight: pull forward a little, then steer toward the gate.</li>' +
    '<li><b>A menu will not close.</b> Right click, or Esc.</li><li><b>I lost the control box, a sign or the roster.</b> F2, look at it, Backspace puts it back where it started.</li><li><b>A door will not open.</b> It is locked: unlock it at the control box.</li><li><b>I am broke.</b> Street deals in the park pay cash at once. The roof greenhouse is free. Sell the cheapest thing you can make and rebuild.</li>' +
    '<li><b>Found a bug?</b> Press <b>F7</b>, or use Report a bug in the pause menu. Fill in the form and it collects your version, your system and your savegame for you. The more of it you fill in, the faster it gets fixed.</li>' +
    '<li><b>Something is badly broken.</b> Pause menu, Dev tools has teleports and a "clear cooldowns" button. Your save lives in the app\'s local storage; "Reset save" in the pause menu starts over.</li></ul>' }
];
