// The player guide. One source for the main menu's guide and the pause menu's "How to play".
// Each chapter is { id, icon, title, html }. Keep it practical: what to press, where to go, what to do when stuck.
window.RF_GUIDE = [
  { id: 'start', icon: '🌱', title: 'Your first ten minutes', html:
    '<p>You start with <b>$220</b>, a small tent, one pot and an empty shop. The goal of the first session is one full loop: seed to sale.</p>' +
    '<ol><li>Walk to the <b>office laptop</b> (the room left of the hall). Order <b>soil</b>, a <b>seed</b>, <b>baggies</b> and, when you can afford it, a <b>grinder</b>.</li>' +
    '<li>Orders come by van to the back. What arrives ends up on the <b>supply rack</b> beside the laptop or as crates in the back room storage; carry crates to the rack yourself, or hire Jo later to do it.</li>' +
    '<li>Take a bag of soil to the <b>grow tent</b>, fill the pot, fetch the seed from the rack, plant it.</li>' +
    '<li>When the plant says thirsty, grab the <b>watering can</b> next to the tent. Feed <b>nutrients</b> once for quality. Spray pests or mold quickly.</li>' +
    '<li>A glowing <b>READY</b> plant is harvested with empty hands. Carry the bunch to the <b>drying line</b> in the dry room and hang it.</li>' +
    '<li>Dried batches jar themselves on the <b>curing shelf</b> and keep gaining quality. Carry a jar to the <b>workbench</b> in the processing room and empty it into the stash.</li>' +
    '<li>At the bench: <b>bag</b> eighths, <b>roll</b> joints (papers and tips), later <b>bake</b> cookies. Finished goods appear on the <b>goods shelf</b>.</li>' +
    '<li>Open the shop at the <b>shop control box</b> (security room, or wherever you hung it). Customers come to the <b>service window</b>. Pick what they asked for off the goods shelf, hand it through the window, then take payment at the <b>register</b>.</li></ol>' +
    '<p>That is the whole game in miniature. Everything else makes that loop bigger, faster or more dangerous.</p>' },
  { id: 'keys', icon: '⌨️', title: 'Controls', html:
    '<table><tr><td><b>W A S D</b></td><td>move</td></tr><tr><td><b>Shift</b></td><td>run</td></tr><tr><td><b>E</b> or left click</td><td>use, pick up, talk, hand over</td></tr><tr><td><b>Shift + E</b></td><td>the second action of a thing (the car trunk, a staff menu, the register drawer)</td></tr>' +
    '<tr><td><b>G</b> or <b>Q</b></td><td>put back what you hold</td></tr><tr><td><b>1 to 6</b>, mouse wheel</td><td>hotbar slot</td></tr><tr><td><b>Tab</b></td><td>inventory</td></tr><tr><td><b>M</b></td><td>town map</td></tr>' +
    '<tr><td><b>P</b></td><td>silent alarm (needs the upgrade)</td></tr><tr><td><b>F2</b></td><td>edit mode: move furniture, signs, screens</td></tr><tr><td><b>F3</b></td><td>creative build mode</td></tr><tr><td><b>Right click</b></td><td>close the open menu or panel</td></tr>' +
    '<tr><td><b>Esc</b></td><td>pause menu</td></tr><tr><td><b>F11</b></td><td>fullscreen (desktop app)</td></tr></table>' +
    '<p><b>In the car:</b> W and S drive, A and D steer, Space brakes, E gets out once you have stopped.</p><p><b>With a weapon in hand:</b> left click swings or fires.</p>' },
  { id: 'grow', icon: '🪴', title: 'Growing and quality', html:
    '<p>Quality is the number that decides your prices and whether connoisseurs buy at all.</p>' +
    '<ul><li><b>Water</b> on time. A thirsty plant loses quality.</li><li><b>Nutrients</b> once per plant: a flat quality bonus.</li><li><b>Pests and mold</b> are hazards: spray them with remedy at once.</li><li><b>Humidity</b>: drying is faster below 55 percent, mold spreads above 60. The dehumidifiers are set at the shop control box.</li><li><b>Lights and tents</b> are bought at the laptop. Bigger tents need the cultivation permits.</li><li><b>Curing</b>: jars keep improving on the shelf. Patience is quality.</li></ul>' +
    '<p>Rough, low quality bud is not wasted. The <b>extraction lab</b> turns any quality into carts, hash, gummies and chocolate. The <b>roof greenhouse</b> grows exactly that kind of bud for free.</p>' },
  { id: 'sell', icon: '🛎️', title: 'Selling', html:
    '<ul><li>An order can have several lines. Hand over each line; the customer pays when it is complete.</li><li>Asked for a strain you do not have? Another strain of the same kind is accepted at 15 percent off. Connoisseurs refuse substitutes and anything under their quality bar.</li>' +
    '<li><b>Cash</b> customers need change from the register. <b>Card</b> needs the retail licence.</li><li>Small extras (lighters, papers, grinders) sit on the counter display and customers help themselves.</li>' +
    '<li><b>Cigarettes, carts, hash, gummies and chocolate</b> are kept in the <b>cabinet behind the counter</b>. Roll the shutter up, take what they asked for, hand it over yourself. It goes on the same bill.</li>' +
    '<li>The <b>markup</b> slider at the control box trades price against footfall.</li><li>Rain, storms and snow thin the street out. Weekends are busier, and there is a holiday week.</li></ul>' },
  { id: 'money', icon: '💵', title: 'Money and the bank', html:
    '<p>Money sits in places: the <b>till</b>, the <b>tip jar</b>, machine cash boxes, your <b>pocket</b>, the <b>vault</b> and the <b>bank</b>. Only the bank is safe and only the bank pays for orders and licences.</p>' +
    '<ul><li>Empty the till into your pocket, then put it in the office <b>vault</b>.</li><li>Book a <b>courier</b> in the bank app: he collects from your pocket at the back door, and it clears the next day.</li><li>Or drive to <b>First Harvest Bank</b> in town and pay it in yourself: instant and free.</li><li>A robber takes what is in the till and tip jar. A gunman goes for the vault next. Pocket cash is lost if you are knocked down, and inspections fine you on it when police heat is high.</li></ul>' },
  { id: 'staff', icon: '🧑‍🔧', title: 'Staff', html:
    '<ul><li><b>Jo</b> (hired at the laptop): serves the window, restocks, sweeps or tends plants. Shift + E on Jo changes the job.</li><li><b>Security guard</b>: checks ID at the door; send him on patrol to deter robbers and break up fights sooner.</li>' +
    '<li>The <b>staff roster</b> board in the office hires three more: a <b>driver</b> (wholesales your cartons every morning and runs phone deliveries), a <b>basement operator</b> (keeps the cigarette line running) and a <b>night guard</b> (stops break-ins).</li><li>Wages leave the bank at the start of each day.</li></ul>' },
  { id: 'crime', icon: '🚨', title: 'Robberies, weapons and the police', html:
    '<p>Robberies run in stages: someone <b>cases</b> the lobby, the <b>mask</b> comes down, the <b>demand</b> at the window, an <b>escalation</b>, sometimes a <b>second target</b> in the back, then the <b>getaway</b>.</p>' +
    '<ul><li>While he is only casing, walk up and press E to confront him. Often he just leaves.</li><li>During the demand, E on the register hands the till over and nobody gets hurt.</li><li>Four kinds, growing with your shop: snatch thief, knife robber, gunman (goes for the vault), two man crew (the bagman strips your goods shelf, and the cabinet if its shutter is up).</li>' +
    '<li><b>Weapons</b>: the bat by the counter is free. The <b>weapon locker</b> sells pepper spray, a taser, and with the firearms licence a pistol and a shotgun. Non lethal tools can fail against dangerous robbers; when they do, he hits back and you go down.</li>' +
    '<li>Shooting an armed, masked robber is self defence. Shooting a fleeing or unarmed man is a fine. Shooting a bystander costs the licence and the guns.</li><li>A robber who escapes with loot jumps into a <b>black car</b> on Main Street. Ram it with yours and everything comes back.</li>' +
    '<li><b>Silent alarm</b> upgrade: press P, police arrive in about 20 seconds.</li><li><b>Doors</b> can be shut and locked from the control box. Staff carry keys; a robber forces a locked door and breaks its lock.</li>' +
    '<li><b>Police heat</b> rises with park deals, fines and shootings and cools with time. At 60 and over you get inspections. The precinct in town shows your heat and takes donations.</li></ul>' },
  { id: 'basement', icon: '🏭', title: 'The basement: RF Smoking', html:
    '<p>The steel hatch in the hall leads down to a pre installed cigarette line. You need the <b>tobacco manufacturing licence</b> to switch anything on.</p>' +
    '<ol><li><b>Bays</b>: sow ($20), wait a few minutes, cut the leaf.</li><li><b>Kiln</b>: cures up to 8 kg a load; leaf dries to a fifth of its weight. Left on, it reloads itself.</li><li><b>Shredder</b> cuts the cured leaf.</li><li><b>Maker</b> rolls Normal or Light sticks.</li><li><b>Packer</b> boxes 10s or 20s and needs paper, filters and blanks, ordered from its own menu.</li><li>Take cartons from the <b>finished goods rack</b> up to the cabinet behind the counter.</li></ol>' +
    '<p>The line makes far more than the window sells. Load cartons into your car at the garage bay (Shift + E on the car) and sell them to the <b>Corner Tobacconist</b> in town, or hire the driver.</p>' },
  { id: 'lab', icon: '🧪', title: 'The extraction lab', html:
    '<p>Its door is on the basement\'s left wall. It takes cured bud of <b>any quality</b> from your stash.</p><ul><li>10 g makes 3 vape carts, or 4 g of pressed hash.</li><li>5 g plus one baking mix makes 12 gummies or 8 chocolate bars.</li><li>One batch at a time. Collect the result from the same equipment and stock it in the cabinet behind the counter.</li><li>A power cut pauses the lab unless you own the generator.</li></ul>' },
  { id: 'town', icon: '🚗', title: 'The town, the car and the map', html:
    '<p>Your car is parked in the owner bay in the yard, behind the gate. The gate opens for it. Press <b>M</b> anywhere for the map.</p>' +
    '<ul><li><b>First Harvest Bank</b>: pay in, withdraw.</li><li><b>Iron and Oak Arms</b>: cheaper ammunition, a Kevlar vest.</li><li><b>RF Supply Co.</b> on the back street: supplies 20 percent cheaper, straight into your trunk. Unload at your bay.</li><li><b>Corner Tobacconist</b>: buys cartons wholesale.</li>' +
    '<li><b>Green Leaf</b>: the rival. Flyer them for reputation; at 150 rep you can buy them out for a daily income.</li><li><b>Harvest Park</b>: street deals at 35 percent over shop price, cash in pocket, with a real risk of a bust.</li><li><b>Police precinct</b>: your heat.</li></ul>' +
    '<p><b>Phone deliveries</b> ring in now and then: a green beacon and a map marker show the address. The <b>garage</b> (Shift + E on the car in its bay) fits a bigger trunk, a tuned engine and a bull bar.</p>' },
  { id: 'upstairs', icon: '🏠', title: 'Upstairs and the roof', html:
    '<ul><li>The <b>office stairs</b> lead to your flat: kitchen, table, couch and TV, bed. Eating gives a speed buff; the bed passes the night.</li><li>The <b>lobby stairs</b> lead to the <b>connoisseur lounge</b>. With the connoisseur permit, guests book it, walk up on their own and wait to be served quality 70 or better. They pay triple and tip.</li><li>A ladder in the flat climbs to the <b>roof greenhouse</b>: six free beds that grow in daylight only.</li></ul>' },
  { id: 'build', icon: '🛠️', title: 'Making the place yours', html:
    '<ul><li><b>F2 edit mode</b>: look at furniture, E grabs, R turns, E drops, Backspace resets. It also carries <b>signs, the dashboard screen, the staff roster and the control box</b>: those stick flat to whatever surface you look at, at any height.</li><li><b>F3 creative mode</b>: a catalogue of furniture and building pieces with finishes and colours. C opens the catalogue, R rotates, the wheel raises, P paints, X copies, Del removes.</li><li>Every door slides with E and can be locked from the control box.</li></ul>' },
  { id: 'stuck', icon: '🧭', title: 'I am stuck', html:
    '<ul><li><b>No customers.</b> Is the shop open at the control box? After a police fine customers stay away for a couple of minutes. Bad weather thins them out.</li><li><b>I cannot pick something up.</b> Hands full: G puts things back, 1 to 6 switches slot.</li><li><b>The customer refuses my goods.</b> Wrong kind, or a connoisseur below his quality bar.</li>' +
    '<li><b>The machines will not start.</b> Tobacco line: you need the licence. Everything stops in a power cut without a generator.</li><li><b>I cannot buy a gun.</b> Firearms licence first (level 4, reputation 30).</li><li><b>My car is wedged.</b> Reverse with S and swing the wheel. The yard is tight: pull forward a little, then steer toward the gate.</li>' +
    '<li><b>A menu will not close.</b> Right click, or Esc.</li><li><b>I lost the control box, a sign or the roster.</b> F2, look at it, Backspace puts it back where it started.</li><li><b>A door will not open.</b> It is locked: unlock it at the control box.</li><li><b>I am broke.</b> Street deals in the park pay cash at once. The roof greenhouse is free. Sell the cheapest thing you can make and rebuild.</li>' +
    '<li><b>Something is badly broken.</b> Pause menu, Dev tools has teleports and a "clear cooldowns" button. Your save lives in the app\'s local storage; "Reset save" in the pause menu starts over.</li></ul>' }
];
