// The player guide. One source for the main menu's guide and the pause menu's "How to play".
// Each chapter is { id, icon, title, html }. Keep it practical: what to press, where to go, what to do when stuck.
// House style: docs/House-Style.md. Run `npm run guide` after an edit so the wiki page matches.
window.RF_GUIDE = [
  { id: 'start', icon: '🌱', title: 'Your first ten minutes', html:
    '<p>You start with <b>$220</b>, a small tent, one pot and an empty shop. There\'s no seed, so that\'s your first buy. The first session has one goal: a full loop, seed to sale.</p><p>A new shop gets the <b>guided intro</b>, a card on the left of the screen that ticks off nine steps as you do them. Finish all nine and <b>$2,500</b> goes into the bank. You can switch it off under <b>Guided intro</b> in the pause menu, but skipping it costs you the bonus.</p>' +
    '<ol><li>Walk to the <b>laptop</b> in the office (the room left of the hall). Order <b>soil</b> and <b>baggies</b> under <b>Supplies</b> and a <b>seed</b> in the <b>Seed bank</b>. Get a <b>grinder</b> too. The workbench won\'t bag or roll without one.</li>' +
    '<li>Orders come round the back in the supplier\'s van. What arrives lands on the <b>supply rack</b> beside the laptop, or as crates in the <b>back room</b>. Carry crates to the supply rack yourself, or hire crew later to do it.</li>' +
    '<li>Take a bag of soil to the <b>grow tent</b> and fill the pot. Fetch the seed from the supply rack and plant it.</li>' +
    '<li>When the plant says it\'s thirsty, grab the <b>watering can</b> next to the tent. Feed it <b>nutrients</b> once for quality. Spray pests or mould straight away.</li>' +
    '<li>A plant that\'s ready glows. Harvest it with empty hands, carry the bunch to the <b>drying line</b> in the dry room and hang it up.</li>' +
    '<li>Dry batches jar themselves on the <b>curing shelf</b> and keep gaining quality. Carry a jar to the <b>workbench</b> in the processing room and empty it into your stash.</li>' +
    '<li>At the workbench, <b>bag</b> eighths or <b>roll</b> joints (papers and tips). Later you can <b>bake</b> cookies. Finished goods go on the <b>goods shelf</b>.</li>' +
    '<li>Open the shop at the <b>control box</b> in the security room, or the <b>front panel</b> behind the till. Customers come to <b>the window</b>. Take what they asked for off the goods shelf, press E on them to hand it over, then take the money at the <b>till</b>.</li></ol>' +
    '<p>That\'s the whole game in miniature. Everything else makes the loop bigger, faster or more dangerous.</p>' },
  { id: 'keys', icon: '⌨️', title: 'Controls', html:
    '<table><tr><td><b>W A S D</b></td><td>move</td></tr><tr><td><b>Shift</b></td><td>run</td></tr><tr><td><b>Space</b></td><td>jump</td></tr><tr><td><b>Ctrl</b></td><td>crouch</td></tr>' +
    '<tr><td><b>E</b> or left-click</td><td>use, pick up, talk, hand over</td></tr><tr><td><b>Shift+E</b></td><td>the second action: lock or unlock with the keyring, the vehicle menu, orders for your crew, open or close the shop van at its hatch</td></tr><tr><td><b>Ctrl+E</b></td><td>send a crew member home</td></tr>' +
    '<tr><td><b>G</b> or <b>Q</b></td><td>put back what you hold</td></tr><tr><td><b>1 to 6</b>, mouse wheel</td><td>hotbar slot</td></tr><tr><td><b>Tab</b></td><td>inventory</td></tr><tr><td><b>M</b></td><td>town map</td></tr>' +
    '<tr><td><b>J</b></td><td>the Deliveries screen: the burner and the tablet</td></tr><tr><td><b>P</b></td><td>silent alarm (needs the upgrade)</td></tr><tr><td><b>F2</b></td><td>edit mode: move furniture, signs, screens</td></tr><tr><td><b>F3</b></td><td>creative build mode</td></tr><tr><td><b>Right-click</b></td><td>close the open menu or panel</td></tr>' +
    '<tr><td><b>F7</b></td><td>report a bug</td></tr><tr><td><b>Esc</b></td><td>pause menu</td></tr><tr><td><b>F11</b></td><td>fullscreen (desktop app)</td></tr></table>' +
    '<p>Jump and crouch don\'t work while you\'re sitting, driving or knocked down. A crouched jump is smaller.</p>' +
    '<p><b>At the wheel:</b> <b>I</b> turns the key, <b>P</b> is the handbrake, <b>L</b> cycles the lights, W and S drive, A and D steer, Space is the footbrake, <b>T</b> opens the boot and <b>B</b> the bonnet. The mouse swings the camera round, the wheel zooms, <b>C</b> re-centres, and <b>E</b> gets you out once you\'ve stopped.</p><p><b>With a weapon in hand:</b> left-click swings or fires.</p>' },
  { id: 'grow', icon: '🪴', title: 'Growing and quality', html:
    '<p>Quality is the number that sets your prices and decides whether connoisseurs buy at all.</p>' +
    '<ul><li><b>Water</b> on time. A thirsty plant loses quality.</li><li><b>Nutrients</b> once per plant: a flat quality bonus.</li><li><b>Pests and mould</b> are hazards. Hit them with <b>pest spray</b> at once.</li><li><b>Humidity</b>: drying is faster below 55%, and mould spreads above 60%. Set the dehumidifiers at the control box.</li><li><b>Lights and tents</b> are bought at the laptop. Bigger tents need the cultivation permits.</li><li><b>Curing</b>: jars keep improving on the curing shelf. Patience is quality.</li></ul>' +
    '<p>Rough, low-quality bud isn\'t wasted. The <b>extraction lab</b> turns any quality into carts, hash, gummies and chocolate. The <b>roof greenhouse</b> grows exactly that kind of bud for free.</p>' },
  { id: 'sell', icon: '🛎️', title: 'Selling', html:
    '<ul><li>An order can have several lines. Hand over each one and they pay once it\'s complete.</li><li>Asked for a strain you haven\'t got? Another strain of the same kind goes at 15% off. Connoisseurs refuse substitutes and anything under their quality bar.</li>' +
    '<li><b>Cash</b> customers need change from the <b>till</b>. <b>Card</b> needs the retail licence.</li><li>Small extras (lighters, papers, grinders) sit on the <b>counter display</b> and customers help themselves.</li>' +
    '<li><b>Cigarettes, carts, hash, gummies and chocolate</b> live in the <b>cigarette cabinet</b> behind the counter. Roll the shutter up, take what they asked for and hand it over yourself. It goes on the same bill.</li>' +
    '<li>The <b>markup</b> slider at the control box trades price against footfall.</li><li>Rain, storms and snow thin the street out. Weekends are busier, and there\'s a holiday week.</li></ul>' },
  { id: 'money', icon: '💵', title: 'Money and the bank', html:
    '<p>Money sits in places: the <b>till</b>, the <b>tip jar</b>, the machine cash boxes, your <b>pocket</b>, the <b>vault</b> and the <b>bank</b>. Only the bank is safe, and only the bank pays for orders and licences.</p>' +
    '<ul><li>Empty the till into your pocket, then put it in the <b>vault</b> in the office.</li><li>Book a <b>courier</b> under <b>Bank</b> on the laptop. He collects from your pocket at the back door and it clears the next morning.</li><li>Or drive to <b>First Harvest Bank</b> in town and pay it in yourself. That\'s instant and free.</li><li>A robber takes what\'s in the till and the tip jar. A gunman goes for the vault next. Pocket cash is lost if you\'re knocked down, and inspections fine you on it when your heat is high.</li><li>Bills fall every morning. Anything the bank can\'t cover comes out of the vault, then the till.</li></ul>' },
  { id: 'staff', icon: '🧑‍🔧', title: 'Staff', html:
    '<ul><li><b>Crew</b>: up to three on the shop floor, <b>Jo</b>, <b>Mika</b> and <b>Sam</b>. Hire them at the laptop under <b>Staff</b>. Each one costs more than the last. They serve the window, restock the supply rack and the machines, sweep, or tend the plants.</li>' +
    '<li><b>The guard</b> is on the door from day one. He checks IDs. Send him on patrol to put robbers off and break up fights sooner, or give him a chore. He\'s back on the door whenever someone walks in.</li>' +
    '<li>The <b>staff roster</b> board in the office hires three more: a <b>driver</b> (wholesales your cartons every morning and runs phone deliveries), a <b>basement operator</b> (keeps the line running) and a <b>night guard</b> (stops break-ins).</li><li>Wages come out at the start of each day: the bank first, then the vault, then the till.</li></ul>' },
  { id: 'crew', icon: '🧑‍🔧', title: 'Your crew day to day', html:
    '<p>Each crew member has their own look, their own job and their own wage.</p>' +
    '<ul>' +
    '<li>Set each one\'s job at the laptop under <b>Staff</b>, or with <b>Shift+E</b> on them: serve the window, restock, sweep, tend the plants, or take a break.</li>' +
    '<li><b>Send home</b> takes someone off the floor for the day. They draw no wage while they\'re off, and <b>Call in</b> brings them back. The guard can be sent home the same way. <b>Ctrl+E</b> on a crew member sends them home on the spot.</li>' +
    '<li><b>Shift+E</b>, then <b>Send them somewhere</b>, posts a crew member. Walk to the spot and press <b>E</b>. That\'s where they wait between jobs until you clear it from the same menu.</li>' +
    '<li>If they\'ve nothing to do, they say so instead of standing there: no dust to sweep, an empty back room, plants already fine.</li>' +
    '</ul>' },
  { id: 'ids', icon: '🪪', title: 'ID checks', html:
    '<p>Every customer carries a real ID, and roughly one in seven won\'t stand up: underage, expired, a photo that isn\'t them, or a plain fake.</p>' +
    '<ul>' +
    '<li>With <b>the guard on the door</b>, they show it to him. He\'s good but not perfect, and now and then he waves a bad one through.</li>' +
    '<li>With <b>the guard off shift</b>, they bring it straight to you at the window. <b>E</b> on them opens the card.</li>' +
    '<li>You can <b>always ask to see it yourself</b>: <b>Shift+E</b> on any customer, even one the guard already passed. That\'s how you catch his mistakes.</li>' +
    '<li>Serve on a bad ID and it\'s on you: heat, rep, and a decent chance of a fine. Refuse a bad one and you gain rep. Refuse a perfectly good one and you lose it.</li>' +
    '</ul>' },
  { id: 'doors', icon: '🚪', title: 'Doors, locks and who gets through them', html:
    '<p>Doors are real to everybody in the building, not just to you.</p>' +
    '<ul>' +
    '<li>A shut door that\'s <b>not locked</b> is no barrier. Crew, the guard and customers push it open as they reach it, and you\'ll see it swing.</li>' +
    '<li>A <b>locked</b> door stops them. Send a crew member somewhere behind one and they give up the errand and tell you it\'s locked, rather than walking through it.</li>' +
    '<li>A <b>robber</b> doesn\'t care what\'s locked, but he can\'t walk through it either. He stops at the door and works on it for a few seconds. You hear it, it goes in the log, and the lock stays broken afterwards. That\'s time you can use.</li>' +
    '<li>So locking the back rooms is worth doing. It won\'t keep a determined man out, but it slows him down and tells you exactly where he is.</li>' +
    '</ul>' },
  { id: 'crime', icon: '🚨', title: 'Robberies, weapons and the police', html:
    '<p>Robberies run in stages: someone <b>cases</b> the lobby, the <b>mask</b> comes down, the <b>demand</b> at the window, an <b>escalation</b>, sometimes a <b>second target</b> in the back, then the <b>getaway</b>.</p>' +
    '<ul><li>While he\'s only casing, walk up and press E to confront him. Often he just leaves.</li><li>During the demand, E on the till hands it over and nobody gets hurt.</li><li>Four kinds, growing with your shop: the <b>snatch thief</b>, the <b>knife robber</b>, the <b>gunman</b> (goes for the vault) and the two-man <b>gang</b> (the bagman strips your goods shelf, and the cigarette cabinet if its shutter is up).</li>' +
    '<li><b>Weapons</b>: the bat by the counter is free. The <b>weapon locker</b> sells pepper spray, a taser, and with the firearms licence a pistol and a shotgun. Non-lethal tools can fail against dangerous robbers. When they do, he hits back and you go down.</li>' +
    '<li>Shooting an armed, masked robber is self-defence. Shooting a fleeing or unarmed man gets you a fine. Shooting a bystander costs you the licence and the guns.</li><li>A robber who gets away with loot jumps into a <b>black car</b> on Main Street. Ram it with yours and everything comes back.</li>' +
    '<li><b>Silent alarm</b> upgrade: press P and the police are there in about 20 s.</li><li><b>Doors</b> can be shut and locked from the control box, or at the door itself with the keyring. A locked door stops your crew too. A robber forces it and breaks the lock.</li><li><b>Lock your stock away.</b> The goods shelf, the cigarette cabinet and the weapon locker all have a roll gate and a lock. A robber who reaches a locked one gets nothing from it. Locking up before closing, or the moment a mask comes down, is the cheapest insurance in the game.</li>' +
    '<li><b>Heat</b> rises with park deals, fines and shootings, and cools with time. At 60 and over you get inspections. The precinct in town shows your heat and takes donations.</li></ul>' },
  { id: 'basement', icon: '🏭', title: 'The basement: RF Smoking', html:
    '<p>The steel hatch in the hall leads down to a pre-installed cigarette line. You need the <b>tobacco manufacturing licence</b> to switch anything on.</p>' +
    '<ol><li><b>Bays</b>: sow ($20), wait a few minutes, cut the leaf.</li><li><b>Kiln</b>: cures up to 8 kg a load, and the leaf dries to a fifth of its weight. Left on, it reloads itself.</li><li><b>Shredder</b>: cuts the cured leaf.</li><li><b>Maker</b>: rolls Normal or Light sticks.</li><li><b>Packer</b>: boxes 10s or 20s. It needs paper, filters and blanks, ordered from its own menu.</li><li>Take cartons from the <b>finished goods rack</b> up to the cigarette cabinet.</li></ol>' +
    '<p>The line makes far more than the window sells. Load cartons into the car at the garage (<b>Shift+E</b> on the car) and sell them to the <b>Corner Tobacconist</b> in town, or hire the driver.</p>' },
  { id: 'lab', icon: '🧪', title: 'The extraction lab', html:
    '<p>Its door is on the basement\'s left wall. It takes cured bud of <b>any quality</b> from your stash.</p><ul><li>10 g makes 3 vape carts, or 4 g of pressed hash.</li><li>5 g plus one baking mix makes 12 gummies or 8 chocolate bars.</li><li>One batch at a time. Collect the result from the same equipment and stock it in the cigarette cabinet.</li><li>A power cut pauses the lab unless you own the generator.</li></ul>' },
  { id: 'town', icon: '🚗', title: 'The town, the car and the map', html:
    '<p>You have two vehicles. The <b>car</b> lives in the <b>garage</b> on the east side of the yard. E on its roller door opens and shuts it, so open it before you drive out. The <b>van</b> stands in the bay under the canopy. Both leave through the <b>yard gate</b>, which opens for you, then down the lane to the back street, where a striped <b>barrier</b> lifts as you drive up and drops behind you. On foot, E opens the gate or raises the barrier. Press <b>M</b> anywhere for the map.</p>' +
    '<p><b>Driving.</b> Press <b>E</b> on the driver\'s door to get in. Both start dead: <b>I</b> turns the key, <b>P</b> lets the handbrake off, then W and S drive and A and D steer. Space is the footbrake. <b>L</b> cycles dipped headlights and main beam, which you\'ll want after dark. The dashboard at the bottom of the screen shows speed, revs, the gear, and lamps for the handbrake, the lights, the ignition and anything left open. The mouse swings the camera round, the wheel pulls it in and out, and <b>C</b> puts it back behind you.</p>' +
    '<p><b>Doors and the boot.</b> Outside, <b>E</b> on the passenger door, the boot or the bonnet opens and shuts it. Inside, <b>T</b> is the boot and <b>B</b> the bonnet. What\'s in the boot sits in the boot, so you can see it. Drive off with something open and the dash warns you, and you won\'t go over 8 km/h. Getting out always puts the handbrake on and stops the engine.</p>' +
    '<ul><li><b>First Harvest Bank</b>: pay in, withdraw.</li><li><b>Iron and Oak Arms</b>: cheaper ammunition, a Kevlar vest.</li><li><b>RF Supply Co.</b> on the back street: supplies 20% cheaper, straight into your boot. Unload them at home with <b>Shift+E</b> on the vehicle.</li><li><b>Corner Tobacconist</b>: buys cartons wholesale.</li>' +
    '<li><b>Green Leaf</b>: the rival. Flyer them for rep. At 150 rep you can buy them out for a daily income.</li><li><b>Harvest Park</b>: street deals at 35% over shop price, cash in your pocket, with a real risk of a bust.</li><li><b>Police precinct</b>: your heat.</li></ul>' +
    '<p><b>Deliveries</b> come on two devices, and <b>J</b> opens both. The next chapter has them. <b>Shift+E</b> on the car at home also fits upgrades: a bigger boot, a tuned engine and a bull bar.</p>' },
  { id: 'rounds', icon: '🚚', title: 'Deliveries: the burner and the tablet', html:
    '<p>Two devices, one key. <b>J</b> opens the <b>Deliveries</b> screen anywhere, on foot or at the wheel, with a tab for each.</p>' +
    '<p><b>The burner.</b> It\'s always in your pocket. Once you\'ve got a couple packed, somebody rings for <b>joints, bags or cookies</b> and gives you an address across town and 5 min. Carry the goods <b>in your hands</b>, drive or walk to the green beacon and press <b>E</b>. The money is cash straight into your <b>pocket</b> at 60% over shop price, and it puts your <b>heat</b> up. No receipt, no tax, and a robber can take it off you, so bank it.</p>' +
    '<p><b>The tablet.</b> It sits on its dock in the office and wakes up the moment you hold the <b>tobacco licence</b>. E takes it. Carry it into the car or the van and it drops into the dash cradle, so it rides the round without taking a hotbar slot. E on the dock puts it back.</p>' +
    '<p>The tablet lists up to four <b>RF Smoking</b> orders at once: an address, how many packs of which cigarette, what it pays and how long is left. Load the packs into the car at the garage (<b>Shift+E</b> on the car), drive the round, and pull up at the amber marker. <b>You don\'t have to get out.</b> Stop within a few metres and the dashboard offers the drop, and <b>E</b> hands it over from the driver\'s seat. The packs come <b>out of the boot</b>, so you never carry them. The money is <b>invoiced to the bank</b>, there\'s no heat, and each drop is worth a point of rep. Jobs further out pay more for the drive.</p>' +
    '<p>Every drop has a coloured ring on the ground under its beacon, and the numbers on the Deliveries screen match the numbers on the <b>map</b> (M). Amber is a tablet drop, green a burner one. Miss a deadline and you lose a point of rep. A hired <b>driver</b> clears jobs himself after about a minute, and takes a cut of the tablet ones.</p>' },
  { id: 'van', icon: '🚐', title: 'The shop van', html:
    '<p>The van in the bay under the canopy is also a shop on wheels. It sells what you put on its rack to whoever walks up, for more than the window gets and with a little more risk.</p>' +
    '<ul><li><b>Shift+E on the serving hatch</b> opens the whole shop van. The hatch lifts, the counter folds out, the tailgate goes up with the rail latched across it, and the OPEN sign lights. Shift+E again packs it all away. E on each piece works it on its own.</li>' +
    '<li><b>E at the open tailgate</b> climbs you into the back. The box is low, so you stoop. E at the tailgate again climbs you out.</li>' +
    '<li>The <b>van rack</b> on the left holds three joints, three bags and three cookies, no more. E on it with goods in your hands stocks it. E with empty hands takes a kind back down.</li>' +
    '<li><b>E on the counter</b> takes the window. Passers-by walk up and ask for what\'s on the van rack, and E on one sells it at half again the shop price. The cash goes in your pocket, and every sale adds a little heat (heat +5).</li>' +
    '<li>Now and then a buyer is a plain-clothes officer. You\'re fined up to $200 and everything of that kind on the van rack is confiscated (heat +20, rep -2). The chance is small, but it grows with your heat.</li>' +
    '<li>Buyers wait about 45 s, then walk off. Move to get up from the window. The <b>van till</b> on the counter shows what the van\'s taken.</li></ul>' },
  { id: 'workshop', icon: '🧩', title: 'The Workshop: content packs', html:
    '<p>The <b>Workshop</b> is on the main menu. Content packs change what the game has in it: more strains to grow, more lamps and tents, more for the counter display, more town, a different car, snow at Christmas or fireworks at New Year. Turn packs on or off, then press <b>Apply and rebuild the shop</b> once and the shop reloads. Your save isn\'t touched, because a pack only adds things you can then go and buy.</p>' +
    '<p><b>Bundles</b> switch several packs on at once. Packs marked <i>one at a time</i> (the balance, seasonal and vehicle ones) replace each other, so you always have exactly one of each.</p>' +
    '<p><b>Making your own.</b> A pack is a single <b>.json</b> file. Use <b>Save a starter .json</b> in the Workshop to get one to edit, then <b>Import a pack</b> to bring it in. It can add:</p>' +
    '<ul><li><b>strains</b>: a whole new plant, with its cost, grow time, yield, strength, unlock level and colours.</li>' +
    '<li><b>lights</b> and <b>tents</b> for the grow room.</li>' +
    '<li><b>supplies</b>: anything you order at the laptop, including things for the counter display or the vending machine.</li>' +
    '<li><b>places</b>: a building and a shopfront anywhere in town, with either a counter that sells supplies at a discount, or a service you pay for that moves your heat and rep. The grocery and the cinema in City Life are nothing more than that.</li>' +
    '<li><b>city</b>: how much bigger the map is, and how many extra blocks fill it.</li>' +
    '<li><b>vehicle</b>: the paint, top speed and boot size of your car.</li>' +
    '<li><b>tune</b>: what seeds and upgrades cost, and how busy the shop is.</li></ul>' +
    '<p><b>Models from Blender.</b> Make the object in Blender, then <b>File, Export, glTF 2.0</b> and choose <b>glTF Binary (.glb)</b>. One metre in Blender is one metre in the game, +Y is up, and the object should sit on the origin. Name the slot it replaces in the pack\'s <b>models</b> section, for example <b>item:joints</b> or <b>item:can</b>, and select the .json and the .glb files together when you import. The model then stands in for whatever the game would have built by hand.</p>' +
    '<p>Packs that ship with the game can\'t be overwritten, so give yours its own id.</p>' },
  { id: 'upstairs', icon: '🏠', title: 'Upstairs and the roof', html:
    '<ul><li>The <b>office stairs</b> lead to your flat: kitchen, table, couch and TV, bed. Eating gives you a speed boost, and the bed sleeps through the night.</li><li>The <b>lobby stairs</b> lead to the <b>connoisseur lounge</b>. With the connoisseur permit, guests book it, walk up on their own and wait to be served quality 70 or better. They pay triple and tip.</li><li>A ladder in the flat climbs to the <b>roof greenhouse</b>: six free beds that grow in daylight only.</li></ul>' },
  { id: 'keyring', icon: '🔑', title: 'The keyring, doors and locking up', html:
    '<p>A keyring hangs on a hook in the <b>office</b>, by the door to the hall. E takes it and G puts it back on the hook. It\'s yours alone, so hang on to it when trouble starts.</p>' +
    '<ul><li><b>Shift+E on a door</b> locks or unlocks it. Step out of the doorway first. Plain <b>E</b> slides a door open or shut as usual, and a locked door won\'t budge.</li>' +
    '<li><b>Shift+E on the goods shelf, the cigarette cabinet or the weapon locker</b> locks it. Locking rolls the gate down. Unlock it and E rolls it back up.</li>' +
    '<li>Without the keyring you can still open and shut anything that\'s unlocked. You just can\'t lock or unlock.</li>' +
    '<li>The control box lists every door with its own shut and lock buttons, plus lock all and unlock all, if you\'d rather do it from one place.</li>' +
    '<li>A locked door stops your crew and the guard too. A robber has to force it, which costs him time.</li></ul>' },
  { id: 'machines', icon: '🥤', title: 'Machines, drinks and the bin', html:
    '<p>Four kinds of machine earn on their own, and you can own more than one of each: up to four vending machines, four coffee machines, four arcade cabinets and three fridges. Buy extras at the laptop under <b>Gear</b>, in the <b>Machines</b> box. Each one costs more than the last.</p>' +
    '<ul>' +
    '<li>A machine you buy lands beside the one you already have, in the first clear space along the same wall. Press <b>F2</b> and drag it where you actually want it. Where you leave it is where it stays.</li>' +
    '<li>Every machine is its own machine. Its door, its delivery tray, the cup under its spout and the cans on its shelves belong to it alone. Open one and the others stay shut.</li>' +
    '<li>Stock and money are the shop\'s, not the machine\'s. All your vending machines sell from the same drinks and snacks, all your coffee machines pour from the same cups and beans, and each kind pays into one cash box. Empty it at any of them.</li>' +
    '<li>The drinks fridge is the exception. Each fridge holds its own cans, because you load it by hand with a case of drinks.</li>' +
    '<li>Extra vending machines come in their own livery, so a row of them doesn\'t look like the same machine four times.</li>' +
    '<li>You need the <b>Lobby coffee machine</b> upgrade before you can buy a second coffee machine. Vending and coffee need the <b>Vending &amp; catering permit</b>, and the arcade the <b>Amusement permit</b>.</li>' +
    '<li>Customers who stay a while use whichever machine they fancy, so more machines means shorter queues.</li>' +
    '</ul>' +
    '<p><b>Drinks and the bin.</b> The <b>water cooler</b> hands you a cup of water. Drink it at the cooler, the couch or the table for a small speed boost (4 min). A coffee or a cold drink does the same at the couch or the table (8 min). Either way you\'re left holding the empty. A cup refills at the cooler, and anything else goes in the <b>bin</b>. The bin holds 12. When it\'s full, E with empty hands bags it up. Take the bin bag to the <b>dumpster</b> in the yard.</p>' },
  { id: 'build', icon: '🛠️', title: 'Making the place yours', html:
    '<ul><li><b>F2 edit mode</b>: look at furniture, E grabs, R turns, E drops, Backspace resets. It also carries <b>signs, the dashboard screen, the staff roster, the key hook, the control box, the front panel and the office panel</b>. Those stick flat to whatever surface you look at, at any height.</li><li><b>F3 creative mode</b>: a catalogue of furniture and building pieces with finishes and colours. C opens the catalogue, R rotates, the wheel raises, P paints, X copies, Del removes.</li><li>Every door slides with E and can be locked from the control box.</li></ul>' },
  { id: 'stuck', icon: '🧭', title: 'I am stuck', html:
    '<ul><li><b>No customers.</b> Is the shop open? The control box and the front panel both switch it. After a police fine, customers stay away for a couple of minutes. Bad weather thins them out.</li><li><b>I can\'t pick something up.</b> Your hands are full. G puts things back, and 1 to 6 switches slot.</li><li><b>The customer refuses my goods.</b> Wrong kind, or a connoisseur and it\'s under his quality bar.</li>' +
    '<li><b>The machines won\'t start.</b> The tobacco line needs its licence. Everything stops in a power cut unless you own the generator.</li><li><b>I can\'t buy a gun.</b> Get the firearms licence first (level 4, rep 30).</li><li><b>My car is wedged.</b> Reverse with S and swing the wheel. The yard is tight, so pull forward a little, then steer towards the gate. Leaving the garage, open the roller door first (E).</li>' +
    '<li><b>A menu won\'t close.</b> Right-click, or Esc.</li><li><b>I lost the control box, a sign or the roster.</b> F2, look at it, and Backspace puts it back where it started.</li><li><b>A door won\'t open.</b> It\'s locked. Unlock it at the control box, or with Shift+E and the keyring.</li><li><b>I\'m broke.</b> Street deals in the park pay cash at once. The roof greenhouse is free. Sell the cheapest thing you can make and rebuild.</li>' +
    '<li><b>Found a bug?</b> Press <b>F7</b>, or use Report a bug in the pause menu. Fill in the form and it collects your version, your system and your savegame for you. The more you fill in, the faster it gets fixed.</li>' +
    '<li><b>Something\'s badly broken.</b> Dev tools in the pause menu has teleports and a button that clears cooldowns. Your save lives in the app\'s local storage, and Reset save in the pause menu starts over.</li></ul>' }
];
