// Writes game/version.js from package.json so the game, the main menu and bug reports all state the same version.
var fs = require('fs'), path = require('path'); var v = require('../package.json').version;
fs.writeFileSync(path.join(__dirname, '..', 'game', 'version.js'), '// generated by tools/sync-version.js from package.json; do not edit\nwindow.RF_VERSION = ' + JSON.stringify(v) + ';\n');
console.log('game/version.js: ' + v);
